# Simplified Pre-commit hooks for Python Trading Framework
# Focused on essential checks without problematic dependencies

repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # Linting with ruff (faster alternative to flake8, no compilation needed)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Basic file checks (local hooks to avoid dependency issues)
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: python -c "import sys; [print(f.rstrip()) for f in sys.stdin]"
        language: system
        types: [text]
        
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: python -c "import sys; content=sys.stdin.read(); sys.stdout.write(content.rstrip() + '\n' if content.strip() else '')"
        language: system
        types: [text]

# Configuration
default_language_version:
  python: python3

# Exclude patterns
exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    __pycache__/|
    \.pytest_cache/|
    \.mypy_cache/|
    build/|
    dist/|
    site/|
    output/|
    logs/|
    .*\.egg-info/|
    trades/.*\.csv|
    data/.*\.csv
  )$ 