site_name: Python交易框架文档
site_description: 企业级Python交易框架的完整技术文档
site_author: Python交易框架团队
site_url: https://your-domain.github.io/python-trading-framework

# Repository
repo_name: python-trading-framework
repo_url: https://github.com/your-repo/python-trading-framework
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Python交易框架团队

# Configuration
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search:
      lang: 
        - zh
        - en

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - tables
  - footnotes

# Navigation
nav:
  - 首页: index.md
  
  - 使用指南:
    - guides/MONITORING.md
    - guides/QUICK_START_PUSH_GUIDE.md
    - guides/GIT_PUSH_BEST_PRACTICES.md
    - guides/M5_MEMORY_OPTIMIZATION_GUIDE.md
    - guides/M4_INCIDENT_RUNBOOK.md
    - guides/MEMORY_OPTIM.md
    - guides/morning_guide.md
  
  - 设计文档:
    - design/ARCHITECTURE.md
    - design/PROJECT_PHASES.md
    - design/DEVELOPMENT_ROADMAP.md
    - design/PROFESSIONAL_TRADING_IMPROVEMENT_PLAN.md
    - design/PROJECT_STRUCTURE_OPTIMIZATION_PLAN.md
  
  - 参考文档:
    - references/API_DOCUMENTATION.md
    - references/DOCKER_DEPLOYMENT.md
    - references/CI_CD.md
    - references/DATA_SOURCES.md
  
  - 发布记录:
    - releases/FINAL_CODE_QUALITY_COMPLETION_REPORT.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-repo/python-trading-framework
    - icon: fontawesome/solid/envelope
      link: mailto:maintainer@example.com

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Custom JavaScript
extra_javascript:
  - javascripts/extra.js 