global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'trading-system'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['trading-system:9090']
    relabel_configs:
      - source_labels: [__address__]
        regex: .*
        target_label: instance
        replacement: 'trading-system' 